Pieter
INF1A-Team-2/Project-B pull request #115
Opened 2023-06-08 10:48 UTC by PieterLandaal

Accounts en check in optie

2023-06-08 11:23 UTC, ZoutigeWolf requested changes

2023-06-08 11:23 UTC, ZoutigeWolf commented on RestaurantManager/DataModels/Account.cs
Points moet ook een parameter hebben in de constructie

2023-06-08 11:23 UTC, ZoutigeWolf commented on RestaurantManager/Presentation/AdminMenu.cs
Vragen voor confirmatie is niet echt nodig, maakt het alleen maar vermoeiender om snel dingen in te checken

2023-06-08 11:28 UTC, PieterLandaal commented on RestaurantManager/DataModels/Account.cs
maar je begint toch altijd met 0 punten?

2023-06-08 11:36 UTC, ZoutigeWolf commented on RestaurantManager/DataModels/Account.cs
Ja maar om het uit de json te kunnen laden moet er een parameter zijn

2023-06-08 11:36 UTC, ZoutigeWolf approved these changes

2023-06-08 11:47 UTC, itsmorbintime123 approved these changes

2023-06-12 11:05 UTC, MrBeast69420 approved these changes

2023-06-12 11:07 UTC, merged