Mrbeast
INF1A-Team-2/Project-B pull request #21
Opened 2023-03-28 08:38 UTC by MrBeast69420

vertaald van engels naar nederlands

2023-03-28 15:33 UTC, ZoutigeWolf requested changes
ziet er goed uit, je moet alleen nog in de ReservationManager een int returnen ipv een bericht printen, en dan in de Program het bericht printen op basis van de status. net zoals pieter heeft gedaan bij cancel reservation

2023-03-29 07:38 UTC, PieterLandaal approved these changes

2023-03-29 08:16 UTC, ZoutigeWolf approved these changes
whatever

2023-03-29 08:28 UTC, itsmorbintime123 approved these changes

2023-03-29 08:32 UTC, merged